//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcCvWebsite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MVCCvWebsiteEntities : DbContext
    {
        public MVCCvWebsiteEntities()
            : base("name=MVCCvWebsiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> About { get; set; }
        public virtual DbSet<Awards> Awards { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Interesteds> Interesteds { get; set; }
        public virtual DbSet<Skills> Skills { get; set; }
        public virtual DbSet<Experience> Experience { get; set; }
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
